package be.ontrack;

import static com.codename1.ui.CN.*;

import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;


/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class MyOnTrackApp extends Lifecycle {
    @Override
    public void runApp() {
        Form hi = new Form("On track", BoxLayout.y());
        Button helloButton = new Button("button click here");
        hi.add(helloButton);

//        NMBSData nmbsData = new NMBSData(AcceptedLanguages.nl);
//        ArrayList arrayList = (ArrayList) nmbsData.getStations().get("station");
//        for (Object o: arrayList) {
//            HashMap hashMap = (HashMap) o;
//            TextField textField = new TextField(hashMap.get("name").toString());
//            hi.add(textField);
//        }

        Label labelVan = new Label("Van:");
        TextField textFieldVan = new TextField();
        Label labelNaar = new Label("Naar:");
        TextField textFieldNaar = new TextField();
        Button buttonSearch = new Button("Search");
        hi.add(labelVan);
        hi.add(textFieldVan);
        hi.add(labelNaar);
        hi.add(textFieldNaar);
        hi.add(buttonSearch);

        textFieldVan.addActionListener();



        helloButton.addActionListener(e -> hello());
        hi.getToolbar().addMaterialCommandToSideMenu("Menu item",
                FontImage.MATERIAL_CHECK, 4, e -> hello());
        hi.show();
    }

    private void hello() {
        Dialog.show("Hello Codename One", "Welcome to Codename One", "OK", null);
    }

}
